### PR TITLE
Rng reseeds

### PR DESCRIPTION
**Pull request by hannesm**
I removed the manual `Rng.reseed` -- why would you do this in the first place?
Once, the Rng is initialised it uses the Lwt event loop to periodically reseed itself, there is no need for manual reseeding. I assume all code pathes call `ssl_.init` once.

### CODE REVIEW

**Comment by gregtatcam** [comment]
no, not all code paths call ssl_.init

can't merge the pull request without breaking the build. other modules that depend on tls have to be fixed first.

**Comment by hannesm** [comment]
I rebased onto master, also opam now contains a more recent conduit, thus the travis build should succeed now

**Comment by gregtatcam** [comment]
merged manually

**Comment by gregtatcam** [comment]
Cool, thanks.

**Comment by hannesm** [comment]
thanks! what are the `Rng.reseed` supposed to do? once initialised, the rng is periodically fed with entropy via the lwt event loop (https://github.com/mirleft/ocaml-nocrypto/blob/master/lwt/nocrypto_entropy_lwt.ml)...

**Comment by gregtatcam** [comment]
These are three cases where Nocrypto_entropy_lwt.initialize () is not called.
Two of them are aes encryption/decryption and one more tls client. I can call the initialize method at the start of each of the application with this cases.

**Pull request closed without merging**
