### PR TITLE
use ppx_deriving, ppx_sexp_conv, and ppx_field_conv; remove lwt.syntax

### PR DESCRIPTION
**Pull request by yomimono**
This is a fairly mechanical update of the codebase to compile in a ppx universe, rather than a camlp4 one.

### CODE REVIEW

**Comment by gregtatcam** [comment]
Travis is failing on these changes ...

**Comment by yomimono** [comment]
Missed the opam update; let's see whether that improves things.

**Comment by gregtatcam** [comment]
It is still a problem.

**Comment by yomimono** [comment]
```
# Error: Files examples/git_store.cmx
#        and /home/travis/.opam/system/lib/git/git.cmxa
#        both define a module named Git_store
```

I don't know how (or whether) you'd like to solve this.  My primary interest is in having a buildable `imaplet-lwt` as it's a reverse dependency for `ocaml-dns`; I'm not a user of this software, and I don't know the codebase well.

**Comment by gregtatcam** [comment]
The error is in Irmin, not imaplet-lwt. It has to be fixed first I presume.

**Pull request closed without merging**
